name: 'Build Format and check'

on:
  push:
    # this list of branches is often enough,
    # but you may still ignore other public branches
    branches-ignore: [release]
  pull_request:
    
    
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: make
      run: make
  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: Install Criterion
      run: |
        sudo apt-get install -y libcriterion-dev
    - name: make test
      run: make test
    

