name: 'Build Format and check'

on:
  push:
    # this list of branches is often enough,
    # but you may still ignore other public branches
    branches-ignore: [release]
  pull_request:
    
    
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: make
      run: make
  format:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - uses: jayllyz/clang-format-action@v1
        # Default options
        with:
          check: false
          style: file
          extensions: cpp,h,hpp,c
          clang-version: latest

      # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(style): clang format files"
          branch: ${{ github.head_ref }}
  Test:
    needs: format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: Install Criterion
      run: |
        sudo apt-get install -y libcriterion-dev
    - name: make test
      run: make test
    

